#!/bin/sh

get_addr () {         
if [ "$1" = "-b" ]; then                   
	op='|'; 
	op1='^'; 
	arg='255'        
	shift                   
else                 
	op='&'         
fi
unset address          
while [ "$5" ]; do                
	num=$(( $1 $op ($5 $op1 $arg) ))               
	shift               
	address="$address.$num"                             
done 
}

shift_network() {
all=(${@//[!0-9]/ })  
get_addr ${all[@]}           
echo "${address#.}" 
} 
