#!/bin/sh
sysctl net.ipv4.ip_forward=1
ip -4 route flush table default scope global
for n in $(/ac/sqlite/bin/sqlite3 /ac/db/ac.s3db "select source_ip,destination_ip from route")
do
	if [ -z "$n" ];then
		break
	fi
	sip=`echo $n|cut -d "|" -f 1`
	#smask=`echo $n|cut -d "|" -f 3`
	dip=`echo $n|cut -d "|" -f 2`
	#dmask=`echo $n|cut -d "|" -f 4`
	
	ip route add $sip table default via $dip scope global
	if [ $? != 0 ];then
		exit -1
	fi
done
